const actionTypes = {
  inputChange: "INPUT_CHANGE",
  adminMovies: "ADMIN_MOVIES",
  request: "REQUEST",
  addSeat: "SEAT_ADD",
  removeSeat: "SEAT_REMOVE",
  reservedSeats: "RESERVED_SEATS",
  response: "RESPONSE",
  userLogin: "USER_LOGIN",
  userLogout: "USER_LOGOUT",
  newTicket: "NEW_TICKET",
  addTicket: "ADD_TICKET",
  removeTicket: "REMOVE_TICKET",
  search: "SEARCH",
  resetReservation: "RESET_RESERVATION",
  changeTheme: "CHANGE_THEME",
  initStore: "INIT_STORE",
  newError: "NEW_ERROR",
};
export { actionTypes };
