const actionTypes = {
  inputChange: "INPUT_CHANGE",
  adminMovies: "ADMIN_MOVIES",
  adminMoviesNotPlaying: "ADMIN_MOVIES_NOT_PLAYING",
  adminUsers: "ADMIN_USERS",
  clearAdmin: "CLEAR_ADMIN",
  request: "REQUEST",
  addSeat: "SEAT_ADD",
  removeSeat: "SEAT_REMOVE",
  reservedSeats: "RESERVED_SEATS",
  response: "RESPONSE",
  getMoviesForHome: "GET_MOVIES_FOR_HOME",
  getMoviesForNowShowing: "GET_MOVIES_FOR_NOW_SHOWING",
  userLogin: "USER_LOGIN",
  userLogout: "USER_LOGOUT",
  userUpdate: "USER_UPDATE",
  newTicket: "NEW_TICKET",
  addTicket: "ADD_TICKET",
  removeTicket: "REMOVE_TICKET",
  search: "SEARCH",
  resetReservation: "RESET_RESERVATION",
  changeTheme: "CHANGE_THEME",
  initStore: "INIT_STORE",
  newError: "NEW_ERROR",
  adminMoviesOfTheMonth: "ADMIN_MOVIES_OF_THE_MONTH",
};
export { actionTypes };
