export const selectors = {
  url: "BASE_URL",
  reservation: "reservation",
  resMovies: "reservation.requests.movies",
  resCinemas: "reservation.requests.cinemas",
  resAuditoriums: "reservation.requests.auditoriums",
  resScreenings: "reservation.requests.screenings",
  resSeats: "reservation.requests.seats",
  resReserved: "reservation.requests.reservedSeats",
  resResponse: "reservation.response",
  inputMovies: "reservation.inputValues.movie",
  inputCinemas: "reservation.inputValues.cinema",
  inputAuditoriums: "reservation.inputValues.auditorium",
  inputScreenings: "reservation.inputValues.screening",
  inputSeats: "reservation.inputValues.seat",
  inputReserved: "reservation.inputValues.reservedSeat",
  inputTickets: "reservation.inputValues.numOfTickets",
  inputSum: "reservation.inputValues.numOfTickets.sum",
  error: "error",
  theme: "theme",
  userInfo: "userInfo",
  tickets: "userInfo.tickets",
  username: "userInfo.username",
  token: "userInfo.token",
  reviews: "userInfo.reviews",
};
