export const actionTypes = {
  GET_MOVIE: "GET_MOVIE",
  GET_NOW_PLAYING: "GET_NOW_PLAYING",
  REQUEST_LOGIN: "REQUEST_LOGIN",
  LOGOUT: "LOGOUT",
  GET_TODAY_MOVIES: "GET_TODAY_MOVIES",
  GET_MOVIES_BY_GENRE: "GET_MOVIES_BY_GENRE",
  GET_UPCOMING_MOVIES: "GET_UPCOMING_MOVIES",
};
