export { UpcomingMovies } from "./upcomingMovies/UpcomingMovies";
export { Ticket } from "./ticket";
export { SeatMatrix } from "./seatsGrid";
export { ReservationContainer as Reservation } from "./reservation";
export { LoginForm } from "./signInForm";
export { GuestSignup } from "./guestSignUp";
export { PromoStudents } from "./Promos";
export { PromoMember } from "./Promos";
export { CardComponent } from "./promoCard";
export { Switch } from "./themeSwitch";
export { MainPhoto } from "./moviePage";
export { MainText } from "./moviePage";
export { SimpleMessage } from "./simpleMessage/SimpleMessage";
export { Home } from "./admin/home/Home";
