export { TicketLayout } from "./ticketLayout/TicketLayout";
export { HomePageLayout } from "./homePage/homePageLayout";
export { ReservationLayout } from "./reservationPage/ReservationLayout";
export { SignInLayout } from "./signInPage/SignInLayout";
export { AboutUsLayout } from "./aboutUsPage/AboutUsLayout";
export { MoviePageLayout } from "./moviePage/MoviePageLayout";
export { CancelPaymentLayout } from "./cancelPaymentLayout/CancelPaymentLayout";
export { default as ThanksForYourPaymentLayout } from "./thanksForYourPayment/ThanksForYouPayment";
export { ThankYouForYourThoughts } from "./thankYouForYourThought/ThankYouForYourThought";
export { AdminPage } from "./adminPage/AdminPage";
